name: Continuous Delivery

on:
  push:
    branches: [ "main" ]

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: simulanaldo Continuous delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozip
          path: |
            '**.py'
            README.md

  deploy:
    needs: cd
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4